### ISSUE TITLE
Add <csolution> element to *.PDSC format

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/Open-CMSIS-Pack-Spec#134]
This is a proposal based on https://github.com/ReinhardKeil/IoT_App/blob/main/ProposedStructure/Proposals.md#changes-to-the-pdsc-file

It replaces to an extend #122

----
/package/csolution element

The \<csolution\> element refers to content in a software pack that can be copied to a project that is managed using the csolution CMSIS project manager. It allows to copy:
  - projects that may be added to a csolution.yml
  - pre-build images that may be added to a csolution.yml
  - software layers that may be added to a cproject.yml
 
**Overall Concept**

The content in the software pack is referred by `{name&variant}` in a csolution.yml or cproject.yml file as shown below.

`*.csolution.yml*`
```yml
solution:
    :
  projects:
    - project:                         # no project specified, scan packs for available project types
      type: PSA&TFM            # Add the PSA base project (variant TFM) for the selected device
    - image:                          # Add a pre-build TFM image for the selected device
      type: TFM
    - project:                         # Add the BootLoader project for the target board
      type: BootLoader
```

`*.cproject.yml`
```yml
project:

  layers:
    - layer:                              # Add board layer to the project
      type: Board
    - layer:                              # alternative to above: Add board layer variant for WiFi
      type: Board&WiFi
```

**Example**
![image](https://user-images.githubusercontent.com/8268058/173306006-382b98af-dcd6-473c-85dc-a5b5a849853e.png)

The \<csolution\> element in the *.PDSC file supports multiple use-cases with these child elements.

Define content in a Software Pack that could be copied to a `csolution` based project.

**Proposed \*.PDSC format**

Parent             | Element Chain                        | Type             | Use
:------------------|:-------------------------------------|:-----------------|:---
csolution          | /package/csolution                   |                  | 0..*
**Attributes**     | **Description**                      | **Type**         | **Use**
description        | Brief description                    | xs:string        | optional
condition          | Enter the id of a condition. The component is available and can be selected when the condition is true.   | xs:string | optional
version            | Content version number. The version format is described in Version Type. |	VersionType | optional
**Child Elements** | **Description**                                             | **Type**         | **Occurrence**
cproject	       | Copy a project from a software pack to a csolution          |                  |
cimage             | Copy a pre-build image from a software pack to a csolution 
clayer             | Copy a pre-configured software layer from a software pack to a cproject

Define the section in a Software Pack that could be copied to a `csolution` based project.

Parent             | Element Chain                        | Type             | Use
:------------------|:-------------------------------------|:-----------------|:---
cproject           | /package/csolution/cproject          |                  | 0..*
cimage             | /package/csolution/cimage            |                  | 0..*
clayer             | /package/csolution/clayer            |                  | 0..*
**Attributes**     | **Description**                      | **Type**         | **Use**
type                | Type of the section                  | xs:string        | required
variant            | Variant of the section               | xs:string        | optional
file                 | File name of the *.yml file that replaces the `{name&variant}` field in the csolution/cproject.yml file. | xs:string  | required
folder             | Relative path to the section base folder within the package. If selected, the directory including all sub-folders and files will be copied to the csolution or cproject base folder. | xs:string | required
isDefaultVariant   | Identifies this section variant to be the preferred variant for tool driven selection | xs:boolean | optional
description        | Brief description                    | xs:string        | required
condition          | Enter the id of a condition. The component is available and can be selected when the condition is true.   | xs:string | optional
version            | Section version number. The version format is described in Version Type. |	VersionType | optional

**Project Lifecycle Management**

Similar to [configuration files](https://github.com/Open-CMSIS-Pack/devtools/blob/main/tools/projmgr/docs/Manual/Overview.md#plm-of-configuration-files) meta files should be implemented that could have the following name format:

```
 {name&variant}.<type>.current@version
 {name&variant}.<type>.update@version
```
The file could be used for a merge utility in case that there are updates to the content.  For that reason, the file should contain meta data, such as the orignal folder and the pack version that was used to copy the content.
