### ISSUE TITLE
Extend spec to support templating languages and use it with generators

### ISSUE THREAD

**Issue by fred-r** [Open-CMSIS-Pack/Open-CMSIS-Pack-Spec#78]
The proposal is to say that:
- a component may have templating language artefacts
- a generator may serve several client components, maybe through software generation via templating engines

We propose extending the specification to allow it, without specifying any mechanism in particular.

Nevertheless, the first application we may foresee is CMSIS-Zone.

**Comment by fred-r** [comment]
Hi Reinhard and all,

regarding the proposal shared during the OpenCMSIS meeting : is it possible to add a 5th file category ?

  - `genParms` template parameters
  - `genHeader` header templates for the generator
  - `genSource` source templates for the generator
  - `genHelper` additional files for the generator

genPartial : partial templates for the generator

And maybe a 6th category, more for layers:

- genSettings : template values selected by the end-user

**Comment by fred-r** [comment]
Another point also in the proposal:

```yml
cgen:
  device: STM32F407IGHx
  board: NucleoF407
  solution: C:/tmp/MySolution/MySolution.csolution.yml 
  project: C:/tmp//MySolution/Blinky/Blinky.cproject.yml 
  context: .Debug+Nucelo    # build-type and target-type of the current generated context
  destination: C:/tmp/MySolution/Blinky/RTE+Nucelo/

  packs:                     # packs that are used for the project
    - pack: Keil::STM32F4xx_DFP@2.16.1
      path: C:/CMSIS-PACKS/Keil/STM32F4xx_DFP/2.16.1/
    - pack: Keil::STM32F4xx_BSP@2.1.1
      path: C:/CMSIS-PACKS/Keil/STM32F4xx_BSP/2.1.1/

  components:               # components that have a genid and are specified in *.cproject.yml
    - component: Device:STM32Cube HAL:Common
    - component: Board:LED
```

For each component, may we have the list of files with the path ?
This way we do not need to evaluate conditions or whatever and we are sure about the files to be provided to the generator.
