### ISSUE TITLE
Handling of packs (Filter, Repositories, Local packs, etc.)

### ISSUE THREAD

**Issue by ReinhardKeil** [Open-CMSIS-Pack/Open-CMSIS-Pack-Spec#85]
Introduce a section `packs:` in `*.csolution.yml` and `*.cdefault.yml` to:
  - reduce the scope of packs used in a project
  - specify pack versions
  - specify local paths to packs

```yml
packs:                                  # start section that specifics software packs
  - filter: AWS::                       # use packs from AWS
  - filter: NXP::*K32L*                 # use packs from NXP that relate to K32L series (would match K32L3A60_DFP + FRDM-K32L3A6_BSP)
  - filter: ARM::                       # use packs from Arm

  - pack: Keil::Arm_Compiler            # add always Keil::Arm_Compiler pack (bypasses filter)
  - pack: Keil::MDK-Middleware@7.13.0   # add Keil::MDK-Middleware pack at version 7.13.0
  - pack: NXP::K32L3A60_DFP             # add pack
    path: .\local\NXP\K32L3A60_DFP      # path to the pack (local copy, repo, etc.)
```
